### ISSUE TITLE
Cannot destructure property 'header' of 'cell' as it is undefined

### ISSUE THREAD

**Issue by frankvollebregt** [gh640/npm-outdated-action#3] opened 2024-10-22 08:05 UTC
Hey, this looks like a neat little action. Unfortunately, it doesn't work for me. The JSON is printed as expected, but an error is thrown while setting up the table/comment.

Have you encountered this before/do you know what might be causing this issue?

Running the current git version or the one in the marketplace does not make a difference. The output below is from the former:
```
TypeError: Cannot destructure property 'header' of 'cell' as it is undefined.
    at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:841:25
    at Array.map (<anonymous>)
    at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:837:18
    at Array.map (<anonymous>)
    at Summary.addTable (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:835:14)
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35424:16), <anonymous>:33:4)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35522:20)
Error: Unhandled error: TypeError: Cannot destructure property 'header' of 'cell' as it is undefined.
```
I'm running the action in a `ubuntu-latest` runner

**Comment by frankvollebregt** [comment] 2024-10-22 08:28
I just set up a minimal project, in which I can also reproduce this issue. You can find it here:
https://github.com/frankvollebregt/npm-outdated-action-test

And here's the actions run:
https://github.com/frankvollebregt/npm-outdated-action-test/actions/runs/11456241969/job/31873947013

**Comment by gh640** [comment] 2024-10-22 09:51
@frankvollebregt 

Thank you for filing the issue.

I myself haven't met the issue and have no idea for now. One thing I found is that the action expects the output of `npm outdated --json` should be one like the following:

```json
{
  "react": {
    "current": "17.0.2",
    "wanted": "17.0.2",
    "latest": "18.3.1",
    "dependent": "test-npm-outdated-action",
    "location": "/home/runner/work/test-npm-outdated-action/test-npm-outdated-action/node_modules/react"
  }
}
```

(sample: https://github.com/gh640/test-npm-outdated-action/actions/runs/11457203779/job/31876954099 ).

But in [your case](https://github.com/frankvollebregt/npm-outdated-action-test/actions/runs/11456241969/job/31873947013), the item in the output doesn't have `current` key.

```json
{
  "pg": {
    "wanted": "8.13.0",
    "latest": "8.13.0",
    "dependent": "npm-outdated-action-test"
  }
}
```

At a glance, I guess it's the cause but I have no idea why and how it happens... I will take a closer look at it later. Thanks!

**Comment by gh640** [comment] 2024-10-22 09:59
@frankvollebregt 

It seems it happens when `npm outdated --json` is used before packages are installed. (In my repositories, I always run `npm ci` before using this action.)

Even when packages are not installed and `current` is missing, the `npm outdated` command can run and this should be fixed. I'll fix it soon.

**Comment by frankvollebregt** [comment] 2024-10-22 10:08
Ah, I see. If I run `npm ci` it does indeed work as expected. I think it's not an odd thing to require, but maybe adding a note to the README or setup guide for the action (and a warning if the packages are not installed?) could be helpful, if you keep it as a requirement.

https://github.com/frankvollebregt/npm-outdated-action-test/actions/runs/11457892445

I'll leave this open in case you want to add a fix and mention it, but feel free to close it, it is now basically resolved for me :)

Thanks!

**Closed as completed** 2024-10-23 01:31 UTC

**Comment by gh640** [comment] 2024-10-23 01:35
@frankvollebregt Thanks for your comment. I created PR #4 and made the fix.

If `current` can't be obtained, it will fall back to the character `-`. I also improved the README a bit.

https://github.com/gh640/npm-outdated-action/pull/4/files

Thanks :)
